version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "unsafe-perm=true" > .npmrc
      - npm install -g serverless
      - npm install
  build:
    commands:
      - |
          CRED=`aws sts assume-role --role-arn arn:aws:iam::377797220092:role/ServerlessDeployRole --role-session-name prod-access`
          echo $CRED
          AWS_ACCESS_KEY_ID=`node -pe 'JSON.parse(process.argv[1]).Credentials.AccessKeyId' "$CRED"`
          AWS_SECRET_ACCESS_KEY=`node -pe 'JSON.parse(process.argv[1]).Credentials.SecretAccessKey' "$CRED"`
          AWS_SESSION_TOKEN=`node -pe 'JSON.parse(process.argv[1]).Credentials.SessionToken' "$CRED"`
          AWS_EXPIRATION=`node -pe 'JSON.parse(process.argv[1]).Credentials.Expiration' "$CRED"`

cache:
  paths:
    - node_modules
    - ${SERVICE_PATH}/node_modules
