version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "unsafe-perm=true" > .npmrc
      - npm install
  build:
    commands:
      - echo "Test alot!"

cache:
  paths:
    - node_modules
    - ${SERVICE_PATH}/node_modules
